' Assigned to: Angelique S. So
' Interface by: Angelique S. So
' Summary: Handles the adding of customer records.
' Date Created: 8/12/2026
' Date Finished: 8/24/2026

Imports IBM.Data.DB2

Public Class frmCustAdd
    Private DBConn As Common.DbConnection

    ' Loading the form
    Private Sub frmCustAdd_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Try
            DBConn = New DB2Connection("server=localhost;database = inkspire;" + "uid = db2admin;password = db2admin;")
            DBConn.Open()

            currDisc8.Checked = False

            dateTimeCustDiscExp.Value = dateTimeCustLastPur.Value.AddDays(30)

            ' Configure Auto ID display
            Me.txtCustId.Text = "(Auto)"
            Me.txtCustId.ReadOnly = True

        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    ' Triggers every time the user picks a new date in the Last Purchase picker
    Private Sub dateTimeCustLastPur_ValueChanged(sender As Object, e As EventArgs) Handles dateTimeCustLastPur.ValueChanged
        dateTimeCustDiscExp.Value = dateTimeCustLastPur.Value.AddDays(30)
    End Sub

    ' SAVE ACTION BUTTON
    Private Sub btnSave_Click(sender As Object, e As EventArgs) Handles btnSave.Click
        ' Validation logic
        If String.IsNullOrWhiteSpace(Me.txtCustLName.Text) Then
            MsgBox("Please input last name.", MsgBoxStyle.Exclamation)
            txtCustLName.Focus()
            Exit Sub
        End If

        If String.IsNullOrWhiteSpace(Me.txtCustFName.Text) Then
            MsgBox("Please input first name.", MsgBoxStyle.Exclamation)
            txtCustFName.Focus()
            Exit Sub
        End If

        Try
            Dim str As String
            Dim cmd As DB2Command
            Dim pr1, pr2, pr3, pr4, pr5, pr6 As DB2Parameter

            ' Call stored procedure with 6 parameters (CustID is generated by DB2 Sequence)
            str = "call ADD_CUSTOMER(?, ?, ?, ?, ?, ?)"
            cmd = New DB2Command(str, DBConn)

            ' Parameter 1: Last Name
            pr1 = cmd.Parameters.Add("@p1", DB2Type.VarChar)
            pr1.Direction = ParameterDirection.Input
            cmd.Parameters("@p1").Value = If(String.IsNullOrWhiteSpace(Me.txtCustLName.Text), DBNull.Value, Me.txtCustLName.Text)

            ' Parameter 2: First Name
            pr2 = cmd.Parameters.Add("@p2", DB2Type.VarChar)
            pr2.Direction = ParameterDirection.Input
            cmd.Parameters("@p2").Value = If(String.IsNullOrWhiteSpace(Me.txtCustFName.Text), DBNull.Value, Me.txtCustFName.Text)

            ' Parameter 3: Middle Initial
            pr3 = cmd.Parameters.Add("@p3", DB2Type.Char)
            pr3.Direction = ParameterDirection.Input
            cmd.Parameters("@p3").Value = If(String.IsNullOrWhiteSpace(Me.txtCustMInitial.Text), DBNull.Value, Me.txtCustMInitial.Text)

            ' Parameter 4: Discount
            Dim VDiscType As Decimal = 0D
            If currDisc8.Checked Then VDiscType = 0.08D
            If currDisc13.Checked Then VDiscType = 0.13D
            If currDisc15.Checked Then VDiscType = 0.15D

            pr4 = cmd.Parameters.Add("@p4", DB2Type.Decimal)
            pr4.Direction = ParameterDirection.Input
            cmd.Parameters("@p4").Value = VDiscType

            ' Parameter 5: Last Purchase Date
            pr5 = cmd.Parameters.Add("@p5", DB2Type.Date)
            pr5.Direction = ParameterDirection.Input
            cmd.Parameters("@p5").Value = Me.dateTimeCustLastPur.Value.Date

            ' Parameter 6: Discount Expiry Date
            pr6 = cmd.Parameters.Add("@p6", DB2Type.Date)
            pr6.Direction = ParameterDirection.Input
            cmd.Parameters("@p6").Value = Me.dateTimeCustDiscExp.Value.Date

            ' Execute Procedure
            cmd.ExecuteNonQuery()

            MsgBox("Success! Customer record added.", MsgBoxStyle.Information)

            ' Clear fields and reset UI
            txtCustLName.Clear()
            txtCustFName.Clear()
            txtCustMInitial.Clear()
            Me.txtCustId.Text = "(Auto)"

        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub

    ' Close form
    Private Sub btnCancel_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
        DBConn.Close()
        Me.Close()
    End Sub
End Class